apiVersion: v1
kind: Service
metadata:
  name: goapp-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    
spec:
  selector:
    app: goapp
  ports:
    - port: 80 #service port 
      targetPort: 8080  #Container port
  type: LoadBalancer